print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/mac/Desktop/unity-gamelab/My project/Assets/models/WhaleWithHeart.mb"`)
{		
	file -o "/Users/mac/Desktop/unity-gamelab/My project/Assets/models/WhaleWithHeart.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/mac/Desktop/unity-gamelab/My project/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/mac/Desktop/unity-gamelab/My project/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/mac/Desktop/unity-gamelab/My project/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
